#pragma config(Sensor, in1,    liftRight,      sensorPotentiometer)
#pragma config(Sensor, in2,    liftLeft,       sensorPotentiometer)
#pragma config(Sensor, in3,    flipPotent,     sensorPotentiometer)
#pragma config(Sensor, in4,    ballIntake,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           intake1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           noUse,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           right2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           right1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           left1,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           left2,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           left3,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           puncher,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          intake2,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////////////////////////////////

// Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

// SmartMotorLibrary
#include "jpearman/SmartMotorLib.c"


#include "Vex_Competition_Includes.c"  // Main competition background code...do not modify!
#pragma systemFile

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code...do not modify!

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////

//PID
//Drive Top Level
// PID using optical shaft encoder
//
// Shaft encoder has 360 pulses per revolution
#define PID_INTEGRAL_LIMIT  50
#define PD_INTEGRAL_LIMIT  50

#define LEFT_SENSOR_INDEX    leftEncoder
#define RIGHT_SENSOR_INDEX   rightEncoder
#define PID_SENSOR_SCALE     -1

#define LEFT_MOTOR_INDEX    left1
#define RIGHT_MOTOR_INDEX   right1
#define PID_MOTOR_SCALE     -1

#define PID_DRIVE_MAX       80
#define PID_DRIVE_MIN     (-80)

// These could be constants but leaving
// as variables allows them to be modified in the debugger "live"


//auton vars
//Left
float  pid_Kp = 0.7;
float  pid_Ki = 0.09;
float  pid_Kd = 0.5;

//Right
float  pd_Kp = 0.7;
float  pd_Ki = 0.09;
float  pd_Kd = 0.5;


static int   pidRunning = 1;
static float pidRequestedValue;

static int   pdRunning = 1;
static float pdRequestedValue;

bool taskRunning=false;

bool driveReverse=false;

/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////

void delayFunc(int time){
	wait1Msec(time);
}

void puncherFunc(int power){
	motor[puncher]=power;
}

void intake1Func(int power1){
	motor[intake1]=power1;
}

void intake2Func(int power2){
	motor[intake2]=power2;
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  pid control task                                                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

void leftFunc(int speed1){
	speed1*=1.1;
	SetMotor(left1,speed1);
	SetMotor(left2,speed1);
	SetMotor(left3,speed1);
}

void rightFunc(int speed2){
	speed2*=1.0;
	SetMotor(right1,speed2);
	SetMotor(right2,speed2);
	SetMotor(right3,speed2);
}

void drive(){
	if(driveReverse==true){
		leftFunc(vexRT[Ch2]*-1);
		rightFunc(vexRT[Ch3]*-1);
	}else if(driveReverse==false){
		rightFunc(vexRT[Ch2]);
		leftFunc(vexRT[Ch3]);
	}
}

void resetEncoders(){
	SensorValue[ leftEncoder ] = 0;
  SensorValue[ rightEncoder ] = 0;
}

task puncherOn(){
	while(true){
		puncherFunc(127);
	}
}

task puncherOff(){
	while(true){
		puncherFunc(0);
	}
}

void turnRight(int rightVal){
	resetEncoders();
  while(SensorValue(leftEncoder) < rightVal)//While leftEncoder has counted less than 1800 counts
	{
		//Turn Right
    rightFunc(-127);// port2 is run at full (127) power forward
		leftFunc(127);      //Motor on port3 is run at full (-127) power reverse	}
	}
}

/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton(){
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
	// Enable smart motor library
	SmartMotorsInit();

	// Define motors plugged into power expander
	// SmartMotorsAddPowerExtender( motorA, motorB, motorC, motorD );

	// Link motors

	// Drive motors
	SmartMotorLinkMotors(left1,left2);
	SmartMotorLinkMotors(left1,left3);
	SmartMotorLinkMotors(right1,right2);
	SmartMotorLinkMotors(right1,right3);
	// Current monitor
	SmartMotorCurrentMonitorEnable();
	// Smart motor start
	SmartMotorRun();
}

/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////

#include "auton.c"

/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////

//auton
void auton(){
	//1200 from place to flag or to alliance park
	//2000 from place to center

	startTask(puncherOn);
	delayFunc(800);
	stopTask(puncherOn);
	startTask(puncherOff);
	stopTask(puncherOff);

	drivePID(1150,1150);
	drivePID(-2000,-2000);
  // If we are using an encoder then clear it
	resetEncoders();

	turnRight(205);

	drivePID(1200,1200);
}

//////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////

task autonomous(){
	auton();
}

//////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////

void clearLCD(){
	clearLCDLine(0);
	clearLCDLine(1);
}

string mainBattery, backupBattery;

//void lcd display voltage
void lcdBattery(){
	bLCDBacklight = true;									// Turn on LCD Backlight

	clearLCD();

	//Display the Primary Robot battery voltage
	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	//Display the Backup battery voltage
	displayLCDString(1, 0, "Backup: ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
	displayNextLCDString(backupBattery);

	//Short delay for the LCD refresh rate
	wait1Msec(100);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////

task usercontrol(){

	// Drive program
	while(true){

	lcdBattery();
	// User control drive functions

	// drive program (find in functions.c)
	drive();

	// Puncher program
	if (vexRT[Btn6U]==1){
		puncherFunc(127);
	}else{
		puncherFunc(0);
	}

	//reverse drive so that you can easily flip caps (find in functions.c)
	if(vexRT[Btn8D]==1){
		if(driveReverse==false){
			waitUntil(vexRT[Btn8D]==0);
			driveReverse=true;
			delayFunc(500);
		}else if(driveReverse==true){
			waitUntil(vexRT[Btn8D]==0);
			driveReverse=false;
			delayFunc(500);
		}
	}

	// Intake program
	if (vexRT[Btn5U]==1){
		 intake1Func(127);
		 intake2Func(127);
		}else if (vexRT[Btn5D]==1){
			intake1Func(-127);
		}else if(vexRT[Btn6D]==1){
			intake2Func(-127);
		}else{
			intake1Func(0);
			intake2Func(0);
		}
	}
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////
