#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  lowerLimit,     sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           liftTop,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           liftBottom,    tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Declare The Positional PID
#define POS_kP 3.5
#define POS_kI 0.4
#define	POS_kD 3.2
#define MAX_HEIGHT 1289

//Declare The Accel/Decel Curve Info
#define SLEW_RATE_SPEED 4.2
#define MAX_SPEED 127

//Declare The Motor Speed Controler
#define SPEED_kP 2
#define SPEED_kI 2
#define SPEED_kD 2
#define HOLDING_POWER 10

//Declare HeightMap
#define LOW 1
#define MED 2
#define TOP 3
#define ZERO 0

//Bools and Ints
int previousError = 0;
float errorSum = 0;
int motPower = 0;

//Just here for testing
void lift(int power)
{
	motor[liftTop] = power;
	motor[liftBottom] = power;
}

//Handles The Position of Lift
void liftPosition(int target)
{
	int error = target - nMotorEncoder[liftBottom];
	int derivative = error - previousError;
	motPower = (error*POS_kP + errorSum*POS_kI + derivative*POS_kD);
	lift(motPower);
	previousError = error;
	errorSum += error / MAX_HEIGHT;
}

void gotoPos(int position)
{
	if(position == LOW)
	{
		liftPosition(254);
	}
	if(position == MED)
	{
		liftPosition(432);
	}
	if(position == TOP)
	{
		liftPosition(1230);
	}
	if(position == ZERO)
	{
		liftPosition(0);
	}
}


//Handles The Accel/Decel Curves
void speedProfile()
{

}

//Handles The Motor Speed
void motorSpeed(int speed)
{

}

//Control Over The Safety Limits
task safetyLimits()
{
	if(SensorValue[lowerLimit] == 1)
	{
		nMotorEncoder[liftBottom] = 0;
		motor[liftBottom] = 0;
		motor[liftTop] = 0;
	}
	if(nMotorEncoder[liftBottom] >= MAX_HEIGHT)
	{
		motorSpeed(0);
	}
}

// Run the Driver Control In Here
task main()
{
	while(69 == 69)
	{
		startTask(safetyLimits);
		gotoPos(TOP);
		gotoPos(ZERO);
	}
}
