#pragma config(Sensor, dgtl1,  leftA,          sensorQuadEncoder)
#pragma config(Motor,  port1,           test,          tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           left1,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           right1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           right2,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		motor[port1] = vexRT[Ch2];
		motor[port10] = vexRT[Ch2];
		//motor[port2] = 127;
		//motor[port3] = 127;
		//motor[port4] = 127;
		//motor[port5] = 127;
	}
}
