#pragma config(Motor,  port1,           north,         tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           east,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           west,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           south,         tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main {
	while(true) {
    int a;
    int b;
    int c;
    int d;

    int u;
    int l;
    int r;
    int dn;

    if((30 < a) && (-30 < b < 30)) {u = true};
    else {u = false};

    if((-30 < a < 30) && (30 < b)) {l = true};
    else {l = false};

    if((-30 < a < 30) && (-30 < b)) {r = true};
    else {r = false};

    if((a < -30) && (-30 < b < 30)) {dn = true};
    else {dn = false};

    if(u = true)
    {
    	motor[port1] = vexRT

    };
	}
}
