#pragma config(Sensor, dgtl1, sa, sensorTouch)
#pragma config(Motor, port2, leftMotor, tmotorVex393, openLoop)
#pragma config(Motor, port3, rightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor, port4, am, tmotorVex393, openLoop)
#pragma config(Motor, port5, cwr, tmotorVex393, openLoop)
#pragma config(Motor, port6, cwl, tmotorVex393, openLoop, reversed)
#pragma config(Motor, port7, am2, tmotorVex393, openLoop, reversed)
//bleebleebloop
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//


#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c" //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
// Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
bStopTasksBetweenModes = true;

// All activities that occur before the competition starts
// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
// Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////



task autonomous()



{
startMotor(rightMotor, 127);
startMotor(leftMotor, -127);
wait(100);
stopMotor(rightMotor);
stopMotor(leftMotor);

}


/////////////////////////////////////////////////////////////////////////////////////////
//
// User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
// User control code here, inside the loop

while (true)
{
// This is the main execution loop for the user control program. Each time through the loop
// your program should update motor + servo values based on feedback from the joysticks.


//Right side of the robot is controlled by the right joystick, Y-axis
motor[rightMotor] = vexRT[Ch2];

//Left side of the robot is controlled by the left joystick, Y-axis
motor[leftMotor] = vexRT[Ch3];



}

if(vexRT[Btn6U] == 1) //If Button 6U is pressed...

{
motor[cwr] = 127; //...close the gripper.
motor[cwl] = 127;
}
else if(vexRT[Btn6D] == 1) //Else, if button 6D is pressed...
{
motor[cwr] = -127; //...open the gripper.
motor[cwl] = -127;
}
else //Else (neither button is pressed)...
{
motor[cwr] = 0; //...stop the gripper.
motor[cwl] = 0;


// Open, close or do not more claw
if(vexRT[Btn5D] == 1) //If Button 6U is pressed...
{
motor[am] = 127; //...close the gripper.
}
else if(vexRT[Btn5U] == 1) //Else, if button 6D is pressed...
{
motor[am] = -127; //...open the gripper.
}
else //Else (neither button is pressed)...
{
motor[am] = 0; //...stop the gripper.
// Open, close or do not more claw
if(vexRT[Btn5U] == 1) //If Button 6U is pressed...
{
motor[am2] = 127; //...close the gripper.
}
else if(vexRT[Btn5D] == 1) //Else, if button 6D is pressed...
{
motor[am2] = -127; //...open the gripper.
}
else //Else (neither button is pressed)...
{
motor[am2] = 0; //...stop the gripper.

}

}
}
}
