#pragma config(Sensor, in1,    liftPotent,     sensorPotentiometer)
#pragma config(Motor,  port2,           left,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           lift1a,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift1b,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift2a,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift2b,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          flipper,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//bleebleebloop
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

/*--
#pragma config(Motor,  port4,           ballIntake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           flyWheel1,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           flyWheel2,     tmotorVex393HighSpeed_MC29, openLoop)
--*/

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c" //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
// Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton(){
// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
bStopTasksBetweenModes = true;

// All activities that occur before the competition starts
// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
// Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////



task autonomous() {

}


/////////////////////////////////////////////////////////////////////////////////////////
//
// User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

//lift functions
void liftUp(){
		motor[lift1a] = -127;
		motor[lift2a] = -127;
		motor[lift1b] = 127;
		motor[lift2b] = 127;
}

void liftDown(){
		motor[lift1a] = 127;
		motor[lift2a] = 127;
		motor[lift1b] = -127;
		motor[lift2b] = -127;
}

void liftStay(){
		motor[lift1a] = 0;
		motor[lift2a] = 0;
		motor[lift1b] = 0;
		motor[lift2b] = 0;
}

//flipper functions
void flip1(){
	motor[flipper]=127;
}

void flip2(){
	motor[flipper]=-127;
}

void flipStay(){
	motor[flipper]=0;
}

//drive function
void drive(){
		motor[left]  = vexRT[Ch3];
		motor[right] = vexRT[Ch2];
}

task usercontrol() {
// User control code here, inside the loop

while (true) {
// This is the main execution loop for the user control program. Each time through the loop
// your program should update motor + servo values based on feedback from the joysticks.

		//MOtor joystick program
		drive();

		//LIft program
		if (vexRT[Btn6D]==1){
			liftUp();
		} else if (vexRT[Btn6U]==1) {
				liftDown();
		} else {
				liftStay();
		}

		//Flipper Program
		if (vexRT[Btn5D]==1) {
			flip1();
		} else if(vexRT[Btn5D]==1){
				flip2();
		} else{
				flipStay();
		}

		/*
		--//flyWheel
		if (vexRT[Btn5D]==1) {
			motor[flyWheel1] = -127;
			motor[flyWheel2] = -127;
			} else if (vexRT[Btn5U]==1) {
			motor[flyWheel1] = 127;
			motor[flyWheel2] = 127;
			} else {
			motor[flyWheel1] = 0;
			motor[flyWheel2] = 0;
		}
		--*/
	}
}
