#pragma config(Motor,  port2,           left1,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           left3,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           right1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           right2,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           right3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ballIntake,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		//variable declarations
		char liftDebug = 0;

		//MOtor joystick program
		motor[port2] = vexRT[Ch3];
		motor[port3] = vexRT[Ch3];
		motor[port7] = vexRT[Ch3];
		motor[port5] = vexRT[Ch2];
		motor[port6] = vexRT[Ch2];
		motor[port4] = vexRT[Ch2];

		//lift program press both buttons at same time
		if((vexRT[Btn5D]==true)&&(vexRT[Btn5U]==true)) {
			char liftDebug=1;
		}

		//LIft program
		while ((vexRT[Btn5D]==true)&&(liftDebug==0)) {
			motor[port8] = -127;
			motor[port9] = -127;
		}
		while ((vexRT[Btn5U]==true)&&(liftDebug==0)) {
			motor[port8] = 127;
			motor[port9] = 127;
		}

		//ball intake
		while (vexRT[Btn5D]==true) {
			motor[port10] = -127;
		}
		while (vexRT[Btn5U]==true) {
			motor[port10] = 127;
		}
	}
}
