#pragma config(Sensor, in1,    liftPotent,     sensorPotentiometer)
#pragma config(Motor,  port1,           left1,         tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           left2,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ballIntake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           flyWheel1,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           flyWheel2,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           right2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           right1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flipper,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	//variable declarations
	int liftDebug = 0;
	while(true) {

		//MOtor joystick program
		motor[left1]  = vexRT[Ch3];
		motor[left2]  = vexRT[Ch3];
		motor[right1] = vexRT[Ch2];
		motor[right2] = vexRT[Ch2];

		//LIft program
		if (vexRT[Btn6D]==1){
			motor[lift1] = -127;
			motor[lift2] = -127;
			} else if (vexRT[Btn6U]==1) {
			motor[lift1] = 127;
			motor[lift2] = 127;
			} else {
			motor[lift1] = 0;
			motor[lift2] = 0;
		}

		//Lift stable
		if((motor[lift1]&&motor[lift2]>=0)&&(SensorValue[in1]<600)) {
			motor[lift1]=127/2;
			motor[lift2]=127/2;
		}

		//flyWheel
		if (vexRT[Btn5D]==1) {
			motor[flyWheel1] = -127;
			motor[flyWheel2] = -127;
			} else if (vexRT[Btn5U]==1) {
			motor[flyWheel1] = 127;
			motor[flyWheel2] = 127;
			} else {
			motor[flyWheel1] = 0;
			motor[flyWheel2] = 0;
		}
	}
}
