#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,            ,             tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,            ,             tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		motor[port2] = vexRT[Ch3];
		motor[port3] = vexRT[Ch3];
		motor[port4] = vexRT[Ch2];
		motor[port5] = vexRT[Ch2];
	}
}
//Additon [VER2]


//I'm pretty sure all the code below has been downloaded to the T-shirt cannon and agreed upon by Michael

task main()
{
	while (true)
	{
		motor[port2] = vexRT[Ch3];
		motor[port3] = vexRT[Ch3];
		motor[port4] = vexRT[Ch2];
		motor[port5] = vexRT[Ch2];


		if (vexRT[Btn5D] == 1)
		{
			motor[port6] = 127;

		}
		else  
		{
			motor[port6] = 0;
		}

		if (vexRT[Btn5U] == 1)
		{
			motor[port7] = 127;
		}
		else
		{
			motor[port7] = 0;
		}
	}




}
