#pragma config(Sensor, dgtl1,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  right,          sensorQuadEncoder)
#pragma config(Motor,  port1,           test1,         tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port10,          test2,         tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Chrome Dome Robotics
task main() {
	motor[port1] = 127;
	motor[port10] = 127;

	/*--
	while (true)
	{
	motor[port2] = vexRT[Ch3];
	motor[port3] = vexRT[Ch3];
	motor[port4] = vexRT[Ch2];
	motor[port5] = vexRT[Ch2];
	}
	--*/
}
