#pragma config(Motor,  port1,           LeftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightDrive,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		motor[port1] = vexRT(Ch2);
		motor[port2] = vexRT(Ch3);

	//	if (vexRT[
		}
}
